name: Merge when green

on:
  push

jobs:
  do-some-build-stuff:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for 20 seconds
        run: sleep 20

  merge-when-green:
    needs: do-some-build-stuff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Merge when green
        run: |
          set +x
          echo "Running git fetch"
          git fetch origin main
          echo "Running git show-ref"
          main_head_sha=$(git show-ref -s origin/main)
          echo "main_head_sha: " $main_head_sha