name: Merge when green

on:
  push

jobs:
  do-some-build-stuff:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for 20 seconds
        run: sleep 20

  merge-when-green:
    needs: do-some-build-stuff
    runs-on: ubuntu-latest
    steps:
      - name: Merge when green
        run: |
          set +x
          main_head_sha=$(git show-ref --heads -s main)
          echo "main_head_sha: " $main_head_sha